symfony/src/Entity/Educations.php
<?php

namespace App\Entity;

use App\Repository\EducationsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EducationsRepository::class)]
class Educations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 30)]
    private $start_date;

    #[ORM\Column(type: 'string', length: 30)]
    private $end_date;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\Column(type: 'text')]
    private $logo;

    #[ORM\ManyToOne(targetEntity: About::class, inversedBy: 'educations')]
    private $owner;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?string
    {
        return $this->start_date;
    }

    public function setStartDate(string $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?string
    {
        return $this->end_date;
    }

    public function setEndDate(string $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getOwner(): ?About
    {
        return $this->owner;
    }

    public function setOwner(?About $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

symfony/src/Controller/EducationsController.php
<?php

namespace App\Controller;

use App\Repository\EducationsRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EducationsController extends CVAbstractController
{
    #[Route('/educations', name: 'app_educations')]
    public function index(EducationsRepository $educationsRepository): Response
    {
        $educationsData = $educationsRepository->findBy(['owner' => $this->user]);

        return $this->render('page/educations/index.html.twig', [
            'educations_data' => $educationsData,
            'current_user'   => $this->user,
        ]);
    }
}

symfony/templates/page/educations/index.html.twig
{% extends 'layout.html.twig' %}

{% block header %}
    {% include 'header.html.twig' %}
{% endblock %}
{% block title %}Hello EducationsController!{% endblock %}

{% block body %}
    <div class="super_container">
        <div class="content_container">
            <div class="main_content_outer d-flex flex-xl-row flex-column align-items-start justify-content-start">
                {{ include('general_info.html.twig') }}
                <div class="main_content">
                    <div class="main_title_container d-flex flex-column align-items-start justify-content-end">
                        <div class="main_subtitle">What I am good at</div>
                        <div class="main_title">My Education</div>
                    </div>
                    <div class="main_content_scroll mCustomScrollbar" data-mcs-theme="minimal-dark">

                        <div class="education">
                            {% for education in educations_data %}
                            <div class="edu_item d-flex flex-lg-row flex-column align-items-start justfy-content-start">
                                <div>
                                    <div class="edu_year">{{ education.startDate ~ ' - ' ~ education.endDate }}</div>
                                </div>
                                <div>
                                    <div class="edu_image"><img
                                                style="width: 60px; height: 60px;"
                                                src="{{ asset('images/' ~ education.logo) }}"
                                                alt="" data-pagespeed-url-hash="1812979664"
                                                onload="pagespeed.CriticalImages.checkImageForCriticality(this);"></div>
                                </div>
                                <div class="edu_content">
                                    <div class="edu_title_container">
                                        <div class="edu_title">{{ education.name }}</div>
                                    </div>
                                    <div class="edu_text">
                                        <p>{{ education.description }}</p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}