symfony/src/Entity/Skills.php
<?php

namespace App\Entity;

use App\Repository\SkillsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SkillsRepository::class)]
class Skills
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'integer')]
    private $symfony;

    #[ORM\Column(type: 'integer')]
    private $angular;

    #[ORM\Column(type: 'integer')]
    private $reactJs;

    #[ORM\Column(type: 'integer')]
    private $php;

    #[ORM\Column(type: 'integer')]
    private $js;

    #[ORM\Column(type: 'integer')]
    private $flutter;

    #[ORM\Column(type: 'integer')]
    private $css;

    #[ORM\Column(type: 'integer')]
    private $years_experience;

    #[ORM\Column(type: 'integer')]
    private $folowers_linkedin;

    #[ORM\Column(type: 'integer')]
    private $projects;

    #[ORM\Column(type: 'integer')]
    private $clients;

    #[ORM\ManyToOne(targetEntity: About::class, inversedBy: 'skills')]
    private $owner;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSymfony(): ?int
    {
        return $this->symfony;
    }

    public function setSymfony(int $symfony): self
    {
        $this->symfony = $symfony;

        return $this;
    }

    public function getAngular(): ?int
    {
        return $this->angular;
    }

    public function setAngular(int $angular): self
    {
        $this->angular = $angular;

        return $this;
    }

    public function getReactJs(): ?int
    {
        return $this->reactJs;
    }

    public function setReactJs(int $reactJs): self
    {
        $this->reactJs = $reactJs;

        return $this;
    }

    public function getPhp(): ?int
    {
        return $this->php;
    }

    public function setPhp(int $php): self
    {
        $this->php = $php;

        return $this;
    }

    public function getJs(): ?int
    {
        return $this->js;
    }

    public function setJs(int $js): self
    {
        $this->js = $js;

        return $this;
    }

    public function getFlutter(): ?int
    {
        return $this->flutter;
    }

    public function setFlutter(int $flutter): self
    {
        $this->flutter = $flutter;

        return $this;
    }

    public function getCss(): ?int
    {
        return $this->css;
    }

    public function setCss(int $css): self
    {
        $this->css = $css;

        return $this;
    }

    public function getYearsExperience(): ?int
    {
        return $this->years_experience;
    }

    public function setYearsExperience(int $years_experience): self
    {
        $this->years_experience = $years_experience;

        return $this;
    }

    public function getFolowersLinkedin(): ?int
    {
        return $this->folowers_linkedin;
    }

    public function setFolowersLinkedin(int $folowers_linkedin): self
    {
        $this->folowers_linkedin = $folowers_linkedin;

        return $this;
    }

    public function getProjects(): ?int
    {
        return $this->projects;
    }

    public function setProjects(int $projects): self
    {
        $this->projects = $projects;

        return $this;
    }

    public function getClients(): ?int
    {
        return $this->clients;
    }

    public function setClients(int $clients): self
    {
        $this->clients = $clients;

        return $this;
    }

    public function getOwner(): ?About
    {
        return $this->owner;
    }

    public function setOwner(?About $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

symfony/src/Controller/SkillsController.php
<?php

namespace App\Controller;

use App\Repository\SkillsRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SkillsController extends CVAbstractController
{
    #[Route('/skills', name: 'app_skills')]
    public function index(SkillsRepository $skillsRepository): Response
    {
        $skillsData = $skillsRepository->findOneBy(['owner' => $this->user]);
        return $this->render('page/skills/index.html.twig', [
            'skills_data' => $skillsData,
            'current_user'   => $this->user,
        ]);
    }
}

symfony/templates/page/skills/index.html.twig
{% extends 'layout.html.twig' %}

{% block header %}
    {% include 'header.html.twig' %}
{% endblock %}
{% block title %}Skills{% endblock %}

{% block body %}
    <div class="super_container">
        <div class="content_container">
            <div class="main_content_outer d-flex flex-xl-row flex-column align-items-start justify-content-start">
                {{ include('general_info.html.twig') }}
                <div class="main_content">
                    <div class="main_title_container d-flex flex-column align-items-start justify-content-end">
                        <div class="main_subtitle">What I am good at</div>
                        <div class="main_title">My Skills</div>
                    </div>
                    <div class="main_content_scroll mCustomScrollbar" data-mcs-theme="minimal-dark">

                        <div class="skills">
                            <div class="skills_text">
                                <div style="column-count: 2">
                                    {{ skills_data.description }}
                                </div>
                            </div>

                            <div class="progress_bars" style="padding-top: 50px">
                                <div class="container-fluid">
                                    <div class="row">

                                        <div class="col-xl-4 col-lg-6 pb_col">
                                            <div class="pb_item">
                                                <div class="p_bar_title">Angular</div>
                                                <div id="skill_1_pbar" class="skill_bars"
                                                     data-perc="{{ skills_data.angular/100 }}"
                                                     data-name="skill_1_pbar" data-color-start="#79ccff"
                                                     data-color-end="#9b74ff"></div>
                                            </div>
                                        </div>

                                        <div class="col-xl-4 col-lg-6 pb_col">
                                            <div class="pb_item">
                                                <div class="p_bar_title">Symfony</div>
                                                <div id="skill_2_pbar" class="skill_bars"
                                                     data-perc="{{ skills_data.symfony/100 }}"
                                                     data-name="skill_2_pbar" data-color-start="#ff4646"
                                                     data-color-end="#ff26d9"></div>
                                            </div>
                                        </div>

                                        <div class="col-xl-4 col-lg-6 pb_col">
                                            <div class="pb_item">
                                                <div class="p_bar_title">ReactJs</div>
                                                <div id="skill_3_pbar" class="skill_bars"
                                                     data-perc="{{ skills_data.reactJs/100 }}"
                                                     data-name="skill_3_pbar" data-color-start="#0054ff"
                                                     data-color-end="#ff23d3"></div>
                                            </div>
                                        </div>

                                        <div class="col-xl-4 col-lg-6 pb_col">
                                            <div class="pb_item">
                                                <div class="p_bar_title">PHP</div>
                                                <div id="skill_4_pbar" class="skill_bars"
                                                     data-perc="{{ skills_data.php/100 }}"
                                                     data-name="skill_4_pbar" data-color-start="#79ff7c"
                                                     data-color-end="#ffbd4a"></div>
                                            </div>
                                        </div>

                                        <div class="col-xl-4 col-lg-6 pb_col">
                                            <div class="pb_item">
                                                <div class="p_bar_title">Js</div>
                                                <div id="skill_5_pbar" class="skill_bars"
                                                     data-perc="{{ skills_data.js/100 }}"
                                                     data-name="skill_5_pbar" data-color-start="#79ff8f"
                                                     data-color-end="#7b74ff"></div>
                                            </div>
                                        </div>

                                        <div class="col-xl-4 col-lg-6 pb_col">
                                            <div class="pb_item">
                                                <div class="p_bar_title">Flutter</div>
                                                <div id="skill_6_pbar" class="skill_bars"
                                                     data-perc="{{ skills_data.flutter/100 }}"
                                                     data-name="skill_6_pbar" data-color-start="#ff2d72"
                                                     data-color-end="#ffab79"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="milestones clearfix" style="padding-top: 50px">

                                <div class="milestone text-center" style="width: 25%; float: left;">
                                    <div class="milestone_icon"><img src="{{ asset('build/images/sun.webp') }}"
                                                                     alt="" data-pagespeed-url-hash="31011354"
                                                                     onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                                    </div>
                                    <div class="milestone_counter" data-end-value="{{ skills_data.yearsExperience }}">
                                        0
                                    </div>
                                    <div class="milestone_text">Years of Experience</div>
                                </div>

                                <div class="milestone text-center" style="width: 25%; float: left;">
                                    <div class="milestone_icon"><img src="{{ asset('build/images/rocket.webp') }}"
                                                                     alt="" data-pagespeed-url-hash="325511275"
                                                                     onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                                    </div>
                                    <div class="milestone_counter" data-end-value="{{ skills_data.clients }}"
                                         data-sign-before="+">0
                                    </div>
                                    <div class="milestone_text">Happy Clients</div>
                                </div>

                                <div class="milestone text-center" style="width: 25%; float: left;">
                                    <div class="milestone_icon"><img src="{{ asset('build/images/user.webp') }}"
                                                                     alt="" data-pagespeed-url-hash="620011196"
                                                                     onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                                    </div>
                                    <div class="milestone_counter" data-end-value="{{ skills_data.folowersLinkedin }}">0
                                    </div>
                                    <div class="milestone_text">Followers on Linkedin</div>
                                </div>

                                <div class="milestone text-center" style="width: 25%; float: left;">
                                    <div class="milestone_icon"><img src="{{ asset('build/images/energy.webp') }}"
                                                                     alt="" data-pagespeed-url-hash="914511117"
                                                                     onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                                    </div>
                                    <div class="milestone_counter" data-end-value="{{ skills_data.projects }}">0</div>
                                    <div class="milestone_text">Finished Projects</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}