symfony/src/Entity/About.php
<?php

namespace App\Entity;

use App\Repository\AboutRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AboutRepository::class)]
class About
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $position;

    #[ORM\Column(type: 'string', length: 100)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 100)]
    private $lastname;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'integer')]
    private $intuition;

    #[ORM\Column(type: 'integer')]
    private $creativity;

    #[ORM\Column(type: 'integer')]
    private $luck;

    #[ORM\Column(type: 'integer')]
    private $awesomeness;

    #[ORM\Column(type: 'text')]
    private $image;

    #[ORM\Column(type: 'string', length: 255)]
    private $location;

    #[ORM\Column(type: 'string', length: 255)]
    private $email;

    #[ORM\Column(type: 'string', length: 255)]
    private $phone_number;

    #[ORM\Column(type: 'string', length: 255)]
    private $birth_date;

    #[ORM\Column(type: 'string', length: 255)]
    private $web_site;

    #[ORM\Column(type: 'string', length: 255)]
    private $linkedin;

    #[ORM\Column(type: 'string', length: 255)]
    private $instagram;

    #[ORM\Column(type: 'string', length: 255)]
    private $facebook;

    #[ORM\Column(type: 'string', length: 255)]
    private $twitter;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Educations::class)]
    private $educations;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Experiences::class)]
    private $experiences;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Services::class)]
    private $services;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Skills::class)]
    private $skills;

    public function __construct()
    {
        $this->educations = new ArrayCollection();
        $this->experiences = new ArrayCollection();
        $this->services = new ArrayCollection();
        $this->skills = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIntuition(): ?int
    {
        return $this->intuition;
    }

    public function setIntuition(int $intuition): self
    {
        $this->intuition = $intuition;

        return $this;
    }

    public function getCreativity(): ?int
    {
        return $this->creativity;
    }

    public function setCreativity(int $creativity): self
    {
        $this->creativity = $creativity;

        return $this;
    }

    public function getLuck(): ?int
    {
        return $this->luck;
    }

    public function setLuck(int $luck): self
    {
        $this->luck = $luck;

        return $this;
    }

    public function getAwesomeness(): ?int
    {
        return $this->awesomeness;
    }

    public function setAwesomeness(int $awesomeness): self
    {
        $this->awesomeness = $awesomeness;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getBirthDate(): ?string
    {
        return $this->birth_date;
    }

    public function setBirthDate(string $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getWebSite(): ?string
    {
        return $this->web_site;
    }

    public function setWebSite(string $web_site): self
    {
        $this->web_site = $web_site;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    /**
     * @return Collection<int, Educations>
     */
    public function getEducations(): Collection
    {
        return $this->educations;
    }

    public function addEducation(Educations $education): self
    {
        if (!$this->educations->contains($education)) {
            $this->educations[] = $education;
            $education->setOwner($this);
        }

        return $this;
    }

    public function removeEducation(Educations $education): self
    {
        if ($this->educations->removeElement($education)) {
            // set the owning side to null (unless already changed)
            if ($education->getOwner() === $this) {
                $education->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Experiences>
     */
    public function getExperiences(): Collection
    {
        return $this->experiences;
    }

    public function addExperience(Experiences $experience): self
    {
        if (!$this->experiences->contains($experience)) {
            $this->experiences[] = $experience;
            $experience->setOwner($this);
        }

        return $this;
    }

    public function removeExperience(Experiences $experience): self
    {
        if ($this->experiences->removeElement($experience)) {
            // set the owning side to null (unless already changed)
            if ($experience->getOwner() === $this) {
                $experience->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Services>
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Services $service): self
    {
        if (!$this->services->contains($service)) {
            $this->services[] = $service;
            $service->setOwner($this);
        }

        return $this;
    }

    public function removeService(Services $service): self
    {
        if ($this->services->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getOwner() === $this) {
                $service->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Skills>
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(Skills $skill): self
    {
        if (!$this->skills->contains($skill)) {
            $this->skills[] = $skill;
            $skill->setOwner($this);
        }

        return $this;
    }

    public function removeSkill(Skills $skill): self
    {
        if ($this->skills->removeElement($skill)) {
            // set the owning side to null (unless already changed)
            if ($skill->getOwner() === $this) {
                $skill->setOwner(null);
            }
        }

        return $this;
    }
}

symfony/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}

    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

symfony/templates/general_info.html.twig
<div class="general_info d-flex flex-xl-column flex-md-row flex-column">
    <div>
        <div class="general_info_image">
            <div class="background_image" style="background-image:url({{ asset('images/' ~ current_user.image) }})"></div>
        </div>
    </div>
    <div class="general_info_content">
        <div class="general_info_content_inner mCustomScrollbar" data-mcs-theme="minimal-dark">
            <div class="general_info_title">General Information</div>
            <ul class="general_info_list">
                <li class="d-flex flex-row align-items-center justify-content-start">
                    <div class="general_info_icon d-flex flex-column align-items-start justify-content-center">
                        <img src="{{ asset('build/images/pencil.webp')}}" alt=""></div>
                    <div class="general_info_text">Name: <span>{{ current_user.firstname ~ ' ' ~ current_user.lastname }}</span></div>
                </li>
                <li class="d-flex flex-row align-items-center justify-content-start">
                    <div class="general_info_icon d-flex flex-column align-items-start justify-content-center">
                        <img src="{{ asset('build/images/web.webp')}}" alt="">
                    </div>
                    <div class="general_info_text">Location: <span>{{ current_user.location }}</span></div>
                </li>
                <li class="d-flex flex-row align-items-center justify-content-start">
                    <div class="general_info_icon d-flex flex-column align-items-start justify-content-center">
                        <img src="{{ asset('build/images/star.webp') }}" alt=""></div>
                    <div class="general_info_text">Date of Birth: <span>{{ current_user.birthdate }}</span></div>
                </li>
                <li class="d-flex flex-row align-items-center justify-content-start">
                    <div class="general_info_icon d-flex flex-column align-items-start justify-content-center">
                        <img src="{{ asset('build/images/message.webp')}}" alt=""></div>
                    <div class="general_info_text">
                        <a href="/cdn-cgi/l/email-protection#6a0905041e0b091e2a0603041b1f0f4409050755191f08000f091e572005083523041b1f031813">
                            <div class="general_info_text">Email: <span class="__cf_email__" data-cfemail="4f2c20213b2e2c3b222a0f3b2a223f232e3b2a212e222a612c2022">
                                            {{ current_user.email }}</span></div></a></div>
                </li>
                <li class="d-flex flex-row align-items-center justify-content-start">
                    <div class="general_info_icon d-flex flex-column align-items-start justify-content-center">
                        <img src="{{ asset('build/images/phone.webp')}}" alt=""></div>
                    <div class="general_info_text">Phone Number: <span>{{ current_user.phoneNumber }}</span></div>
                </li>
            </ul>

            <div class="social_container">
                <ul class="d-flex flex-row align-items-start justify-content-start">
                    <li><a href="#"><i class="fa-brands fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="{{ current_user.linkedin }}" target=”_blank”><i class="fa-brands fa-linkedin" aria-hidden="true"></i></a></li>
                    <li><a href="{{ current_user.instagram }}" target=”_blank”><i class="fa-brands fa-instagram" aria-hidden="true"></i></a></li>
                    <li><a href="{{ current_user.facebook }}" target=”_blank”><i class="fa-brands fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="{{ current_user.twitter }}" target=”_blank”><i class="fa-brands fa-twitter" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

symfony/templates/header.html.twig
{% set current_path = app.request.get('_route') %}

{% block header %}
    <div class="offcanvas-menu">
        <a href="/" class="site-logo">
            <img src="{{ asset('images/logo.png') }}" alt="logo">
        </a>
        <nav class="mobile__menu"></nav>
    </div>
    <header class="header">
        <div class="header_content d-flex flex-row align-items-center justify-content-start">
            <div class="logo">Samoil<span>.</span>CV</div>
            <div class="main_nav d-flex flex-row align-items-end justify-content-start">
                <ul class="d-flex flex-row align-items-center justify-content-start">
                    <li class="active"><a href="{{ path('app_about') }}">About</a></li>
                    <li><a href="{{ path('app_skills') }}">Skills</a></li>
                    <li><a href="{{ path('app_services') }}">Services</a></li>
                    <li><a href="{{ path('app_experiences') }}">Experience</a></li>
                    <li><a href="{{ path('app_educations') }}">Education</a></li>
                    <li><a href="{{ path('app_contact') }}">Contact</a></li>
                </ul>
            </div>

            <div class="menu" style="background: blue">
                <div class="menu_content d-flex flex-row align-items-start justify-content-end">
                    <div class="hamburger ml-auto">menu</div>
                    <div class="menu_nav text-right">
                        <ul>
                            <li><a href="{{ path('app_about') }}">About</a></li>
                            <li><a href="{{ path('app_skills') }}">Skills</a></li>
                            <li><a href="{{ path('app_services') }}">Services</a></li>
                            <li><a href="{{ path('app_experiences') }}">Experience</a></li>
                            <li><a href="{{ path('app_educations') }}">Education</a></li>
                            <li><a href="{{ path('app_contact') }}">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

symfony/templates/layout.html.twig
<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>
    <title>About</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="vCard template project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css" integrity="sha512-OivR4OdSsE1onDm/i3J3Hpsm5GmOVvr9r49K3jJ0dnsxVzZgaOJ5MfxEAxCyGrzWozL9uJGKz6un3A7L+redIQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Philosopher" />
    <script src="{{ asset('build/plugins/js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ asset('build/styles/bootstrap-4.1.2/popper.js') }}"></script>
    <script src="{{ asset('build/styles/bootstrap-4.1.2/bootstrap.min.js') }}"></script>
    <script src="{{ asset('build/plugins/greensock/TweenMax.min.js') }}"></script>
    <script src="{{ asset('build/plugins/greensock,_TimelineMax.min.js+scrollmagic,_ScrollMagic.min.js+greensock,_animation.gsap.min.js+greensock,_ScrollToPlugin.min.js.pagespeed.jc.wtdVidDD2e.js') }}"></script>
    <script src="{{ asset('build/plugins/progressbar/progressbar.js') }}"></script>
    <script src="{{ asset('build/plugins/plugins,_easing,_easing.js+plugins,_parallax-js-master,_parallax.min.js+js,_education.js.pagespeed.jc.t7H3cQJ84O.js') }}"></script>
    <script src="{{ asset('build/plugins/plugins,_easing,_easing.js+plugins,_parallax-js-master,_parallax.min.js+js,_contact.js.pagespeed.jc.mUHUan8tjF.js') }}"></script>
    <script src="{{ asset('build/plugins/plugins,_easing,_easing.js+plugins,_parallax-js-master,_parallax.min.js+js,_experience.js.pagespeed.jc.k8Mmx6KXIN.js') }}"></script>
    <script src="{{ asset('build/plugins/plugins,_easing,_easing.js+plugins,_parallax-js-master,_parallax.min.js+js,_services.js.pagespeed.jc.eY83JPzP4D.js') }}"></script>
    <script src="{{ asset('build/plugins/mCustomScrollbar/jquery.mCustomScrollbar.js') }}"></script>
    <script src="{{ asset('build/plugins/plugins,_easing,_easing.js+plugins,_parallax-js-master,_parallax.min.js+js,_custom.js.pagespeed.jc.Rb_NLULxCA.js') }}"></script>
    <script src="{{ asset('build/plugins/plugins,_easing,_easing.js+plugins,_parallax-js-master,_parallax.min.js+js,_skills.js.pagespeed.jc.2IZHCv7LVg.js') }}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>eval(mod_pagespeed_jXpAJz1XpV);</script>
    <script>eval(mod_pagespeed_479Yn8bvzx);</script>
    <script>eval(mod_pagespeed_cQz899P46w);</script>
    <script>eval(mod_pagespeed_RL09Ilmv43);</script>
    <script>eval(mod_pagespeed_tu1cRxfRa1);</script>
    <script>eval(mod_pagespeed_4n6WSHGpTp);</script>
    <script>eval(mod_pagespeed_2hysw07FMH);</script>
    <script>eval(mod_pagespeed_JeFeMLgLr7);</script>
    <script>eval(mod_pagespeed_6nPsaHdPI8);</script>
    <script>eval(mod_pagespeed_pyUm5wxaZM);</script>
    <script>eval(mod_pagespeed_NOsQjGyGwE);</script>
    <script data-pagespeed-no-defer>//<![CDATA[
        (function(){for(var g="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[c]=a.value)},h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,k=["String","prototype","repeat"],l=0;l<k.length-1;l++){var m=k[l];m in h||(h[m]={});h=h[m]}
            var n=k[k.length-1],p=h[n],q=p?p:function(b){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var a="";b;)if(b&1&&(a+=c),b>>>=1)c+=c;return a};q!=p&&null!=q&&g(h,n,{configurable:!0,writable:!0,value:q});var t=this;
            function u(b,c){var a=b.split("."),d=t;a[0]in d||!d.execScript||d.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===c?d[e]?d=d[e]:d=d[e]={}:d[e]=c};function v(b){var c=b.length;if(0<c){for(var a=Array(c),d=0;d<c;d++)a[d]=b[d];return a}return[]};function w(b){var c=window;if(c.addEventListener)c.addEventListener("load",b,!1);else if(c.attachEvent)c.attachEvent("onload",b);else{var a=c.onload;c.onload=function(){b.call(this);a&&a.call(this)}}};var x;function y(b,c,a,d,e){this.h=b;this.j=c;this.l=a;this.f=e;this.g={height:window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth};this.i=d;this.b={};this.a=[];this.c={}}
            function z(b,c){var a,d,e=c.getAttribute("data-pagespeed-url-hash");if(a=e&&!(e in b.c))if(0>=c.offsetWidth&&0>=c.offsetHeight)a=!1;else{d=c.getBoundingClientRect();var f=document.body;a=d.top+("pageYOffset"in window?window.pageYOffset:(document.documentElement||f.parentNode||f).scrollTop);d=d.left+("pageXOffset"in window?window.pageXOffset:(document.documentElement||f.parentNode||f).scrollLeft);f=a.toString()+","+d;b.b.hasOwnProperty(f)?a=!1:(b.b[f]=!0,a=a<=b.g.height&&d<=b.g.width)}a&&(b.a.push(e),
                b.c[e]=!0)}y.prototype.checkImageForCriticality=function(b){b.getBoundingClientRect&&z(this,b)};u("pagespeed.CriticalImages.checkImageForCriticality",function(b){x.checkImageForCriticality(b)});u("pagespeed.CriticalImages.checkCriticalImages",function(){A(x)});
            function A(b){b.b={};for(var c=["IMG","INPUT"],a=[],d=0;d<c.length;++d)a=a.concat(v(document.getElementsByTagName(c[d])));if(a.length&&a[0].getBoundingClientRect){for(d=0;c=a[d];++d)z(b,c);a="oh="+b.l;b.f&&(a+="&n="+b.f);if(c=!!b.a.length)for(a+="&ci="+encodeURIComponent(b.a[0]),d=1;d<b.a.length;++d){var e=","+encodeURIComponent(b.a[d]);131072>=a.length+e.length&&(a+=e)}b.i&&(e="&rd="+encodeURIComponent(JSON.stringify(B())),131072>=a.length+e.length&&(a+=e),c=!0);C=a;if(c){d=b.h;b=b.j;var f;if(window.XMLHttpRequest)f=
                new XMLHttpRequest;else if(window.ActiveXObject)try{f=new ActiveXObject("Msxml2.XMLHTTP")}catch(r){try{f=new ActiveXObject("Microsoft.XMLHTTP")}catch(D){}}f&&(f.open("POST",d+(-1==d.indexOf("?")?"?":"&")+"url="+encodeURIComponent(b)),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.send(a))}}}
            function B(){var b={},c;c=document.getElementsByTagName("IMG");if(!c.length)return{};var a=c[0];if(!("naturalWidth"in a&&"naturalHeight"in a))return{};for(var d=0;a=c[d];++d){var e=a.getAttribute("data-pagespeed-url-hash");e&&(!(e in b)&&0<a.width&&0<a.height&&0<a.naturalWidth&&0<a.naturalHeight||e in b&&a.width>=b[e].o&&a.height>=b[e].m)&&(b[e]={rw:a.width,rh:a.height,ow:a.naturalWidth,oh:a.naturalHeight})}return b}var C="";u("pagespeed.CriticalImages.getBeaconData",function(){return C});
            u("pagespeed.CriticalImages.Run",function(b,c,a,d,e,f){var r=new y(b,c,a,e,f);x=r;d&&w(function(){window.setTimeout(function(){A(r)},0)})});})();

        pagespeed.CriticalImages.Run('/mod_pagespeed_beacon','https://preview.colorlib.com/theme/vcard2/skills.html','-ilGEe-FWC',true,false,'rx4hdW7hK-Y');
        //]]></script>
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}
    {{ encore_entry_script_tags('app') }}
</head>
<body>
{% block header %}{% endblock %}
{% block body %}{% endblock %}
{% block footer %}
    {% block footer_space %}{% endblock %}
{% endblock %}
</body>
</html>